system:
  daemon: on

mps:
  #1-Ordinary service 2-Quality service
  node_type: 1 
  region: center
  #1:domain  2:ipv4  3:ipv6
  net_type: 2
  jwt_timeout: 120
  #1:hls  2:rtsp
  protocol_type: 1

scc:
  config-path: /opt/holo/mps/config/scc.conf

log:
  path: /opt/log/mps/run/
  # debug info warn error nolog
  level: debug
  # console file
  mode: file
  file_keep_days: 2
  file_keep_num: 10

server:
  live:
    device_timeout: 30
    client_timeout: 30
    data_timeout: 11
modules:
  hls:
    wan_ip: "${wan_ip:-127.0.0.1}"
    lan_ip: "${listen_ip:-127.0.0.1}"
    listen: 7081
  rtsp:
    wan_ip: "${wan_ip:-127.0.0.1}"
    lan_ip: "${listen_ip:-127.0.0.1}"
    listen: 7082

cert_key:
  ivm_cert_path: /opt/certs/user_cert.pem
  local_key_path: /opt/certs/user_cert.key
unix:
  addr: /opt/holo/amah_agent/amah_agent.sock

apollo:
  appid: IVMHoloMediaProxyService
  cluster: $apollo_cluster
  namespace:
#    - "global.jwt.interface"
#    - "paas.jwt.stream"
    - "global.jwt"
    - "global.register.center"
    - "global.certs"
    - "global.elb.inside"
    - "billing.rabbitmq"
    - "application"
  cache_dir: ./
  meta_addr: $apollo_addr
